---
- name: Adjust max map count
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
  become: true

- name: Setup directories
  file:
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ paths.FILEBEAT }}"
    - "{{ paths.ELASTICSEARCH }}"

- name: Sync filebeat config
  synchronize:
    src: files/filebeat.yml
    dest: "{{ paths.FILEBEAT }}"
  notify:
  - change ownership

- name: Sync filebeat ECS fields
  synchronize:
    src: files/fields.yml
    dest: "{{ paths.FILEBEAT }}"
  notify:
  - change ownership

- name: Sync Pensando filebeat module
  synchronize:
    src: files/module
    dest: "{{ paths.FILEBEAT }}"
  notify:
  - restart filebeat
