- hosts: localhost
  become: true
  tasks:
  - name: install python modules.
    shell: "dnf install --nobest python3 python-dnf"

  - name: Remove existing unofficial Docker packages
    dnf:
      name: "{{ item }}"
      state: absent
    with_items:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux

  - name: Install dnf-plugins-core to manage DNF repository
    dnf:
      name:  dnf-plugins-core
      state: present

  - name: Add docker repo
    shell:  'dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo'

  - name: Update dnf package index
    dnf:
     name: docker-engine
     state: latest

  - name: Start docker service
    systemd:
      state: started
      name: docker
