- hosts: localhost
  become: true
  tasks:
  - name: Install python modules.
    shell: "dnf install python3"
    args:
      warn: false
  - name: Install dnf-plugins-core to manage DNF repository
    shell: "dnf -y install dnf-plugins-core"
    args:
      warn: false

  - name: Add docker repo
    shell:  'dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo'
    args:
      warn: false

  - name: Install containerd
    shell: "dnf -y install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"

  - name: Install Docker
    shell: "dnf -y install docker-ce docker-ce-cli"
    args:
      warn: false

  - name: Start docker service
    systemd:
      state: started
      name: docker
