- hosts: localhost
  become: true
  tasks:
  - name: Install python modules.
    shell: "dnf install python3 python-dnf"
    args:
      warn: false
  - name: Install dnf-plugins-core to manage DNF repository
    shell: "dnf -y install dnf-plugins-core"
    args:
      warn: false

  - name: Add docker repo
    shell:  'dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo'
    args:
      warn: false

  - name: Install Docker and Containerd
    shell: "dnf -y install docker-ce docker-ce-cli containerd.io"

  - name: Start docker service
    systemd:
      state: started
      name: docker
