- hosts: localhost
  become: true
  tasks:
  - name: Install python modules.
    shell: "dnf install python3 python-dnf"
    args:
      warn: false

  - name: Remove existing unofficial Docker packages
    shell: "dnf remove --installed docker docker-common container-selinux docker-selinux"
    args:
      warn: false

  - name: Install dnf-plugins-core to manage DNF repository
    dnf:
      name:  dnf-plugins-core
      state: present

  - name: Add docker repo
    shell:  'dnf config-manager \
      --add-repo \
      https://download.docker.com/linux/centos/docker-ce.repo'

  - name: Update dnf package index
    dnf:
     name: docker-engine
     state: latest

  - name: Start docker service
    systemd:
      state: started
      name: docker
