---
- name: Start elastiflow-logstash
  docker_container:
    image: robcowart/elastiflow-logstash-oss:4.0.0-beta
    name: elastiflow-logstash-oss
    volumes:
      - '{{ paths.ELASTIFLOW }}/ipfix.yml:/etc/logstash/elastiflow/definitions/ipfix.yml:ro'
    network_mode: host
    restart_policy: always
    env:
      # JVM Heap size - this MUST be at least 3GB (4GB preferred)
      LS_JAVA_OPTS: "{{ logstash.EF_LS_JAVA_OPTS }}"
      # ElastiFlow global configuration
      ELASTIFLOW_DEFAULT_APPID_SRCTYPE: "__UNKNOWN"
      ELASTIFLOW_RESOLVE_IP2HOST: "false"
      ELASTIFLOW_NAMESERVER: "{{ lookup('env', 'DNS_IP') | default('8.8.8.8', true) }}"
      ELASTIFLOW_NETFLOW_IPV4_PORT: '2055'
      ELASTIFLOW_SFLOW_IPV4_PORT: '6343'
      ELASTIFLOW_IPFIX_TCP_IPV4_PORT: '4739'
      ELASTIFLOW_IPFIX_UDP_IPV4_PORT: '4739'
      ELASTIFLOW_ES_HOST: http://{{ lookup('env', 'ELASTICSEARCH_HOST') | default('127.0.0.1', true) }}:9200