---
- name: Start kibana
  docker_container:
    image: docker.elastic.co/kibana/kibana:{{ lookup('env', 'ELK_TAG') | default('7.8.0', true) }}
    name: kibana
    network_mode: host
    env:
        SERVER_HOST: 0.0.0.0
        SERVER_PORT: '5601'
        SERVER_MAXPAYLOADBYTES: '4194304'
        ELASTICSEARCH_HOSTS: http://{{ lookup('env', 'ELASTICSEARCH_HOST') | default('127.0.0.1', true) }}:9200
        KIBANA_DEFAULTAPPID: 'dashboard/653cf1e0-2fd2-11e7-99ed-49759aed30f5'
        LOGGING_DEST: 'stdout'
        LOGGING_QUIET: 'false'