---
- name: Start kibana
  docker_container:
    image: docker.elastic.co/kibana/kibana:{{ lookup('env', 'ELK_TAG') | default('7.14.0', true) }}
    name: kibana
    network_mode: host
    restart_policy: always
    env:
        SERVER_HOST: 0.0.0.0
        SERVER_PORT: '5601'
        SERVER_MAXPAYLOADBYTES: '4194304'
        ELASTICSEARCH_HOSTS: http://{{ lookup('env', 'ELASTICSEARCH_HOST') | default('127.0.0.1', true) }}:9200
        KIBANA_DEFAULTAPPID: 'dashboard/3548db90-cc62-11ea-918e-c778f7abe5d7'
        LOGGING_DEST: 'stdout'
        LOGGING_QUIET: 'false'

- name: Checking that kibana is up and running
  wait_for:
    port: 5601
    delay: 30
