---
- name: Setup Pensando filebeat configuration
  docker_container:
    name: pensando-filebeat-setup
    image: docker.elastic.co/beats/filebeat:{{ lookup('env', 'ELK_TAG') | default('7.8.0', true) }}
    user: root
    volumes:
      - '{{ paths.FILEBEAT }}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - '{{ paths.FILEBEAT }}/fields.yml:/usr/share/filebeat/fields.yml:ro'
      - '{{ paths.FILEBEAT }}/module/pensando:/usr/share/filebeat/module/pensando:ro'
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      strict.perms: 'false'
      setup.kibana.host: https://{{ lookup('env', 'KIBANA_HOST') | default('127.0.0.1', true) }}:5601
      output.elasticsearch.hosts: http://{{ lookup('env', 'ELASTICSEARCH_HOST') | default('127.0.0.1', true) }}:9200
    network_mode: host

- name: Pausing playbook so filebeat config can be transferred
  wait_for:
    timeout: 15
  delegate_to: localhost
